- root/lib/rsetup/tui/comm/comm.sh
- root/lib/rsetup/tui/hardware/hardware.sh
- root/lib/rsetup/tui/system/system.sh
- root/lib/rsetup/tui/user/user.sh
> New branch

- root/lib/rsetup/tui/comm/comm.sh
- root/lib/rsetup/tui/hardware/hardware.sh
- root/lib/rsetup/tui/system/system.sh
- root/lib/rsetup/tui/user/user.sh
With those features completed, Chean modified hardware.sh after tests on board
Led list can function now.
Signed-off-by: cheanz<zhangchenge@radxa.com>
@RadxaYuntian
> Comm, hardware, system and user.

- src/usr/lib/rsetup/cli/u-boot-menu.sh
resolves https://github.com/radxa-build/radxa-cm3-io/issues/8
> perf: modify dtbo_is_compatible location for rebuild_overlays

- src/usr/lib/rsetup/cli/u-boot-menu.sh
- src/usr/lib/rsetup/tui/overlay/overlay.sh
resolves https://github.com/radxa-pkg/rsetup/issues/34
> feat: add cli function enable_overlays

- src/usr/lib/rsetup/cli/wi-fi.sh
* revised https://github.com/radxa-build/radxa-zero3/issues/7
> fix: fix rsetup.service running connect_wi-fi error on startup

- Makefile
- debian/control
- src/usr/lib/rsetup/tui/local/local.sh
- src/usr/lib/rsetup/tui/main.sh
- src/usr/lib/rsetup/tui/overlay/overlay.sh
- src/usr/lib/rsetup/tui/system/system.sh
> feat: add the function to switch default target

- debian/rsetup.install
- src/usr/share/bash-completion/completions/rsetup
> feat: add test/mpp bash-completion

- src/usr/lib/rsetup/tui/hardware/hardware.sh
Fix incoming non-existent video device
> fix: hardware: video: persistent RTUI_MENU_SELECTED variable

- src/usr/lib/rsetup/tui/system/system.sh
* closes https://github.com/radxa-pkg/rsetup/issues/53
> fix: modify options for querying available_targets

- src/usr/lib/rsetup/tui/system/system.sh
* closes https://github.com/radxa-pkg/rsetup/issues/57
> fix: correct the erase bootloader prompt message

- src/usr/lib/rsetup/cli/baota.sh
- src/usr/lib/rsetup/cli/main.sh
- src/usr/lib/rsetup/tui/main.sh
- src/usr/lib/rsetup/tui/task/baota/baota.sh
- src/usr/lib/rsetup/tui/task/task.sh
This PR adds Baota panel to the common tasks section of rsetup
> Add baota to rsetup

- debian/control
* 关联 https://github.com/radxa-pkg/rsetup/pull/62#issuecomment-2190504329
> chore: update librtui

- src/usr/lib/rsetup/mod/pkg.sh
> fix: use reliable method to check package status

- debian/control
- src/usr/lib/rsetup/tui/overlay/overlay.sh
- src/usr/lib/rsetup/tui/system/system.sh
> fix: bootloader: add support judgment for operations

- debian/control
- src/usr/lib/rsetup/tui/hardware/hardware.sh
* closes https://github.com/radxa-pkg/rsetup/issues/72
> fix: use services.json to identify available udc services

- src/usr/lib/rsetup/tui/hardware/hardware.sh
* closes https://github.com/radxa-pkg/rsetup/issues/75
> fix: hardware: otg: modify to disable function before enable

- debian/control
- src/usr/lib/rsetup/cli/baota.sh
- src/usr/lib/rsetup/tui/task/baota/baota.sh
- src/usr/lib/rsetup/tui/task/task.sh
* closes https://github.com/radxa-pkg/rsetup/issues/74
> fix: task: change to use checklist

- config/before.txt
- src/usr/lib/rsetup/cli/system.sh
> feat: add generic hostname update function

- src/usr/lib/rsetup/tui/hardware/hardware.sh
Link:  https://applink.feishu.cn/client/message/link/open?token=Ami%2F2XW%2Fg4ADaNigoGtBABM%3D
> fix: fix some errors when using USB cameras

- src/usr/lib/rsetup/cli/system.sh
- src/usr/lib/rsetup/mod/get_setup_script.sh
- src/usr/lib/rsetup/tui/system/system.sh
https://applink.feishu.cn/client/message/link/open?token=AmfHwOsK4gAEaNoxaJJmgAQ%3D
> feat: add edk2 support for bootloader management
